name: "Daily activity digests"

on:
  push:
    branches:
      - "**/*digest*"
  schedule:
    # 1pm UTC, so 8/9am Eastern.
    # https://crontab.guru/#02_13_*_*_*
    - cron: "02 13 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  digest:
    name: "Daily digest"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: 3.8

      - name: "Install tools"
        run: |
          python -m pip install dinghy

      - name: "Run dinghy"
        env:
          # Made with nedbat's account, with public_repo, read:org, read:project
          GITHUB_TOKEN: ${{ secrets.DINGHY_ACCESS_TOKEN }}
        run: |
          python -m dinghy --verbosity=debug || \
          python -m dinghy --verbosity=debug || \
          python -m dinghy --verbosity=debug || \
          exit 1

      - name: Send failure notification
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          server_port: 465
          username: ${{secrets.EDX_SMTP_USERNAME}}
          password: ${{secrets.EDX_SMTP_PASSWORD}}
          subject: Dinghy digest failed in ${{github.repository}}
          to:  ned@edx.org
          from: github-actions <github-actions@edx.org>
          body: Dinghy digest in ${{github.repository}} failed! For details see github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.

      - name: "Publish digests"
        run: |
          set -xe
          git status
          git add *.html
          git stash
          git fetch --all
          git switch digests
          git reset --hard origin/digests-base
          git stash pop
          git config --global user.email "ned@edx.org"
          git config --global user.name "dinghy digester"
          git commit -am "docs: latest digests"
          git push --force
